name: Scheduled test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * 6'
  workflow_dispatch:

jobs:
  tests:
    name: Test API compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Provide test properties
        run: |
          echo "irdataapi.user=$IRDATAAPI_USER" > src/test/resources/application-test.properties
          echo "irdataapi.password=$IRDATAAPI_PASSWORD" >> src/test/resources/application-test.properties
          echo "irdataapi.logResponseJson=false" >> src/test/resources/application-test.properties
          echo "irdataapi.cache-directory=.cache" >> src/test/resources/application-test.properties
          echo "irdataapi.hashPassword=true" >> src/test/resources/application-test.properties
          echo "logging.level.root=INFO" >> src/test/resources/application-test.properties
          cat src/test/resources/application-test.properties
        env:
          IRDATAAPI_USER: ${{secrets.IR_USERNAME}}
          IRDATAAPI_PASSWORD: ${{secrets.IR_PASSWORD}}
      - name: Compliance Test
        id: compliance-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn --batch-mode --update-snapshots verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=simracingtools_ir-data-api-client -Dmaven.test.skip=false -Pcoverage
      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify failed tests
    needs: tests
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: jayqi/failed-build-issue-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title-template: "Compliance test failed"
          label-name: "Failed test"
          body-template: |
            GitHub Actions workflow [{{workflow}} #{{runNumber}}](https://github.com/{{repo.owner}}/{{repo.repo}}/actions/runs/{{runNumber}}) failed.